name : "Development "
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
#    steps:
#
##      - name: Checkout code
##        uses: actions/checkout@v2
#
##      - name: Make gradlew executable
##        run: chmod +x ./gradlew
##
##      - name: Generate Release APK
##        run: ./gradlew assembleDebug
#
##      - uses: actions/upload-artifact@master
##        with:
##          path: app/build/outputs/apk/debug/*.apk
      - name: Get sample .apk for test purposes
        run: wget --output-document ApiDemos-debug.apk https://github.com/alexkrl/GithubActionPlayground/blob/master/app/app-debug.apk?raw=true
#
      - name: upload artefact to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: alexTexel/GithubActionPlayground
          token: 3dcd32803a093e957c3c1d5dfdfadf317c7d0fd8
          group: Collaborators
          file: ApiDemos-debug.apk
          notifyTesters: false
          debug: true






#      - uses: actions/upload-artifact@master
#        with:
#          path: app/build/outputs/apk/prod/release/*.apk
#
#      - uses: actions/upload-artifact@master
#        with:
#          name: dev_mapping.txt
#          path: app/build/outputs/mapping/devRelease/mapping.txt
#
#      - uses: actions/upload-artifact@master
#        with:
#          name: prod_mapping.txt
#          path: app/build/outputs/mapping/prodRelease/mapping.txt
